### ISSUE TITLE
1.4.0 tag missing

### ISSUE THREAD

**Issue by glensc** [chef/mixlib-authentication#19]
looks like 1.4.0 tag was not pushed:
https://github.com/chef/mixlib-authentication/releases

perhaps even some more commits to master missing?

https://rubygems.org/gems/mixlib-authentication has more versions than in github:
- 1.4.0 - January 19, 2016 (22 KB)
- 1.4.0.rc.1 - December 16, 2015 (22 KB) 
- 1.4.0.rc.0 - December 11, 2015 (22 KB)

**Comment by tas50** [comment]
1.4.0 tag now pushed
