### ISSUE TITLE
Version 1.4.3 breaks the Chef gem < 14, berks, and Chefspec gems

### ISSUE THREAD

**Issue by Dan-Kitchen** [chef/mixlib-authentication#34]
Hi,

Earlier today we had builds starting to fail around our chef cookbooks and roles uploads. Upon inspecting I determined that this is caused by version 1.4.3 of `mixlib-authentication`, albeit kind of indirectly.

As you can see both have errors using the chef-linked gems:

> **Roles - using berks**
> bundler: failed to load command: berks (/var/app/jenkins/bundles/ruby/2.3.0/bin/berks)
> NoMethodError: undefined method `trace' for #<Logger:0x007f6f5f75f578>
> 
> **App cookbook - chefspec**
> + bundle exec rspec
> 
> Chef encountered an error attempting to load the node data for "chefspec"
> 
> Unexpected Error:
> NoMethodError: undefined method `trace' for #<Logger:0x007fe5444919a8>
> Did you mean? trace_var
> trap

This gem is used by basically any gem that wants to speak to the Chef server. This includes chefspec, berks (via ridley gem) etc. This is made worse by those gems in question having the following version requirements:

chef (versions 12.x and 13.x): (~> 1.4)
ridley (5.1.1): (>=1.3.0)

It appears this change: https://github.com/chef/mixlib-authentication/pull/32/commits/23e5b6782725f646ad40bdc38b5ece50bf044534
Depends on this in the mixlib-log gem (in version 2.1.0) : https://github.com/chef/mixlib-log/commit/6bf78bb5803f11ef832e8e0b15151ae9b130eeb7#diff-19783d72fc4cc244ae938eef663eb3a9

However, walking and resolving our gemfile dependencies doesn't give us this version. Our Chef gems (of varying versions) ask for mixlib-log (~> 1.3) picking up 1.7.0. This causes it to go boom with this version of mixlib-authentication.

`mixlib-authentication` is a dependency of the chef gem and berkshelf (via the Ridley gem). Version 1.4.3 which uses functionality from `mixlib-log` but this functionality was only added in `mixlib-log` 2.1.0 and this version isn’t a dependency of `mixlib-authentication`.

The issue in our case is the versions of the chef gem/berkshelf we use want `mixlib-log (~> 1.3)`. This causes it to blow up because the functionality used by `mixlib-authentication` isn’t present in the version of `mixlib-log` we pull in (1.7.0). I expect this isn’t the case in Chef 14 but this essentially breaks the chef (12/13) gems with this change. All the chef versions before 14 and berkshelf/ridley want `mixlib-authentication ~> 1.4` hence when 1.4.3 was released it gets pulled in and causes the chef and berkshelf gems to break.

I'm not sure what the best fix is here but this is basically a breaking change via dependencies and it being a patch release isn't being great as it is being picked up everywhere as shown above.

**Comment by Dan-Kitchen** [comment]
We've had to pin our version in all our gemfiles to 1.4.2 to stop this breaking for us.

**Comment by thommay** [comment]
The offending release has already been yanked.

**Comment by Dan-Kitchen** [comment]
Thanks Thom! Have removed our pins and no longer failing
